### ISSUE TITLE
Typo in prod-system function in systems.clj

### ISSUE THREAD

**Issue by kajism** [danielsz/system-dependency-injection#2]
I guess on line 28 should be the same code as on line 18, so now it would result in invalid arity error, when production system started.

**Comment by danielsz** [comment]
Fixed. 

Thank you very much, @kajism

**Comment by kajism** [comment]
You are welcome. I'm new to Clojure and your libraries and it's documentation are very helpful! Thank you very much @danielsz!

**Comment by danielsz** [comment]
You sure show a lot of promise for a newcomer :-) :+1:
