### ISSUE TITLE
Suggestion for a neater DI of db into server api functions

### ISSUE THREAD

**Issue by kajism** [danielsz/system-dependency-injection#3]
The system/components/app.clj is quite a fresh file, so maybe this could be considered:

"A closure is also neater than attaching the database connection to the request map; we need only destructure it once, rather than in every route." -- James Reeves

https://www.booleanknot.com/blog/2015/05/22/structuring-clojure-web-apps.html

**Comment by danielsz** [comment]
This is very interesting. I will be looking into it. 
I will also gladly accept a PR if you're up for it.
Thank you, @kajism.
